### ISSUE TITLE
Arquivo barra.js inexistente

### ISSUE THREAD

**Issue by emerson-pj** [marceloalencar/joomla-4.x#5]
Boa tarde povo, tudo blz ?

Sabem dizer sobre o arquivo javascrit da Barra padrão dos sites do Gov, será foi descontinuada ?
Lembro que o JS foi útil quando mostrou a campanha do mosquito e da Covis.
Pergunto isso pelo fato dos caminhos ao arquivo .js estarem inoperantes. São eles:
http://barra.brasil.gov.br/barra.js
http://barra.brasil.gov.br/barra_2.0.js
https://barra.brasil.gov.br/barra_2.0.js

Esses endereços são especificados no manual Identidade Visual do Governo Federal na Internet:
https://barra.governoeletronico.gov.br/instrucoes.html#id2

Sabem dizer qual seria o novo endereço desses arquivos javascript ?

**Comment by marceloalencar** [comment]
Boa tarde!

A barra com a URL https://barra.brasil.gov.br/barra.js (notar o s de https) está funcionando aqui, da mesma forma que https://barra.brasil.gov.br/barra_2.0.js também funcionou.

Exemplos:
https://labdemon.ufpa.br/ (Barra 1.0)
https://editora.ufpa.br/ (Barra 2.0)

**Comment by emerson-pj** [comment]
Vlw, pela informação.
O problema está na minha rede, não somente no servidor de hospedagem, mas a rede interna também não está deixando acessar o barra.js, nem se eu colocar diretamente no navegador (https://barra.brasil.gov.br/barra_2.0.js).
